-- ================================================
-- Template generated from the mo-cli-tool for 
-- postgrator. https://github.com/parksjr/mo-cli-tool
--
-- Add undo actions as needed.
--
-- Make the necessary changes to fulfill your needs.
--
-- This block of comments will not be included in
-- the definition of the procedure.
-- ================================================